color0 #131315
color1 #ffb4ab
color2 #c4c4e5
color3 #c7c5d4
color4 #e3bbd3
color5 #c4c4e5
color6 #c7c5d4
color7 #e5e1e4
color8 #919098
color9 #ffb4ab
color10 #c4c4e5
color11 #c7c5d4
color12 #e3bbd3
color13 #c4c4e5
color14 #c7c5d4
color15 #e5e1e4

cursor                #e5e1e4
cursor_text_color     #131315
background            #131315
foreground            #e5e1e4
selection_foreground  #c8c5ce
selection_background  #47464d
active_border_color   #c4c4e5
inactive_border_color #47464d
url_color             #c4c4e5

active_tab_foreground   #2d2e48
active_tab_background   #c4c4e5
inactive_tab_foreground #c8c5ce
inactive_tab_background #47464d
cursor_trail_color      #c8c5ce
